name: self-hosted

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose -f $GITHUB_WORKSPACE/docker-compose.yml --env-file /opt/merkist-development/.env up --build -d
          until docker compose -f $GITHUB_WORKSPACE/docker-compose.yml --env-file /opt/merkist-development/.env exec -T api python -c "import app" 2>/dev/null; do sleep 2; done
          docker compose -f $GITHUB_WORKSPACE/docker-compose.yml --env-file /opt/merkist-development/.env exec -T api aerich upgrade || true
          docker image prune -f